import styled from "@emotion/styled";
import { motion } from "framer-motion";
import type AtomWrapperTypes from "./types";

export const AtomWrapper = styled(motion.div)<AtomWrapperTypes>`
  display: flex;
  height: ${(props) => props.height ?? "100%"};
  width: ${(props) => props.width ?? "100%"};
  gap: ${(props) => props.gap ?? "0px"};
  margin: ${(props) => props.margin ?? "0px"};
  max-width: ${(props) => props?.maxWidth || `100%`};
  max-height: ${(props) => props?.maxHeight || `initial`};
  border: ${(props) => props?.border || `none`};
  justify-content: ${(props) => props?.justifyContent || `center`};
  align-items: ${(props) => props?.alignItems || `flex-start`};
  background-image: ${(props) => props?.backgroundImage};
  background-color: ${(props) => props?.backgroundColor || `transparent`};
  background-position: center;
  background-size: ${(props) => props?.backgroundSize || `cover`};
  outline: ${(props) => props?.outline || `none`};
  min-height: ${(props) => props?.minHeight || `initial`};
  max-width: ${(props) => props.maxWidth ?? "none"};
  border-radius: ${(props) => props?.borderRadius || `0px`};
  background-color: ${(props) => props.backgroundColor ?? "transparent"};
  flex-wrap: ${(props) => props.flexWrap ?? "nowrap"};
  flex-direction: ${(props) => props.flexDirection ?? "column"};
  padding: ${(props) => props.padding ?? "0px"};
  z-index: ${(props) => props?.zIndex || `0`};
  position: ${(props) => props?.position || `static`};
  cursor: ${(props) => props?.cursor || `default`};
  mix-blend-mode: ${(props) => props?.mixBlendMode || `normal`};
  ${(props) => props?.customCSS};
`;
export default AtomWrapper;
